table confusion_matrix
	lineageTag: 8f100680-f7bd-41b9-84c0-71050af8a84d

	column actual_class
		dataType: string
		lineageTag: de07f3f8-82ac-496b-9b52-42cd87cad3fd
		summarizeBy: none
		sourceColumn: actual_class

		annotation SummarizationSetBy = Automatic

	column predicted_class
		dataType: string
		lineageTag: e09e3024-2dc1-474c-87e2-139b475178d0
		summarizeBy: none
		sourceColumn: predicted_class

		annotation SummarizationSetBy = Automatic

	column classification_result
		dataType: string
		lineageTag: 68263b88-6e38-4462-9a66-40bf56622056
		summarizeBy: none
		sourceColumn: classification_result

		annotation SummarizationSetBy = Automatic

	column count
		dataType: int64
		formatString: 0
		lineageTag: 2958ada6-7288-4006-ae30-1416d7ba71ac
		summarizeBy: sum
		sourceColumn: count

		annotation SummarizationSetBy = Automatic

	partition confusion_matrix = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Sami Data Set\powerbi\confusion_matrix.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"actual_class", type text}, {"predicted_class", type text}, {"classification_result", type text}, {"count", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

