table model_metrics
	lineageTag: 6204f1cd-e490-4ba1-b6f8-d8ba4295a220

	column metric
		dataType: string
		lineageTag: 62704623-43a3-4b60-9544-2c502a8ff0cf
		summarizeBy: none
		sourceColumn: metric

		annotation SummarizationSetBy = Automatic

	column value
		dataType: double
		lineageTag: 81bb4491-26c2-4aeb-bb18-fae5b661aab4
		summarizeBy: sum
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition model_metrics = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Sami Data Set\powerbi\model_metrics.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"metric", type text}, {"value", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

